version: '3.8'

services:
  my-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped